#!/usr/bin/env python3
"""
IEEE Control Algorithm Research Hub
Bridging academic research → engineering implementation

研究流水线:
  [论文搜索] → [深度分析] → [代码生成] → [CI/CD验证]
     ieee_search.py  paper_analyzer.py   hub.py        pipeline.yml
"""

import os
import sys
import json
import logging
import subprocess
from datetime import datetime
from typing import Dict, Any, List

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S"
)
logger = logging.getLogger("IEEE-Hub")

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
HERMES_DIR = os.path.join(SCRIPT_DIR, "agents", "hermes")
RESEARCH_DIR = os.path.join(SCRIPT_DIR, "research", "reports")
IMPLEMENTATIONS_DIR = SCRIPT_DIR


class ResearchHub:
    """Central dispatch: paper analysis → code generation"""

    def __init__(self):
        os.makedirs(RESEARCH_DIR, exist_ok=True)
        os.makedirs(IMPLEMENTATIONS_DIR, exist_ok=True)

    # ───────── Research stage ─────────

    def search_papers(self, query: str, max_results: int = 5) -> List[Dict]:
        """Step 1: Search papers from multiple sources (Semantic Scholar + OpenAlex)"""
        sys.path.insert(0, HERMES_DIR)
        from ieee_search import search_papers as ss_search

        logger.info(f"🔍 Search papers: {query}")
        result = ss_search(query, max_results=max_results)
        papers = result.get("results", [])
        logger.info(f"→ {len(papers)} papers found")
        return papers

    def analyze_paper(self, doi: str) -> str:
        """Step 2: In-depth analysis of the paper → Generate Markdown report"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_doi = doi.replace("/", "_").replace(".", "_")
        output = os.path.join(RESEARCH_DIR, f"analysis_{safe_doi}.md")

        logger.info(f"📖 Analysis paper: {doi}")
        result = subprocess.run(
            [sys.executable, os.path.join(HERMES_DIR, "paper_analyzer.py"),
             "--doi", doi, "--lang", "zh", "--output", output],
            capture_output=True, text=True, timeout=60
        )

        if os.path.exists(output):
            logger.info(f"✅ Report saving: {output}")
            return output
        else:
            logger.error(f"❌ Analysis failed: {result.stderr[:200]}")
            return ""

    # ───────── Code generation phase ─────────

    def generate_code(self, report_path: str, category: str = "hysteresis") -> str:
        """Step 3: Extract the mathematical model from the analysis report to generate code"""
        target_dir = os.path.join(IMPLEMENTATIONS_DIR, category, "src")
        os.makedirs(target_dir, exist_ok=True)

        logger.info(f"⚙️ Generated code: {os.path.basename(report_path)} → {category}/")

        # Read report to extract mathematical model description
        with open(report_path, encoding="utf-8") as f:
            report = f.read()

        # Extract abstract and methodology sections
        sections = {"abstract": "", "methodology": "", "innovation": ""}
        current = ""
        for line in report.split("\n"):
            if "# # 📝 summary" in line:
                current = "abstract"
            elif "# # 🔬 Methodology" in line:
                current = "methodology"
            elif "# ##Innovation point" in line or "## 🏷️" in line:
                current = "innovation"
            elif line.startswith("## ") and current:
                current = ""

            if current in sections:
                sections[current] += line + "\n"

        # Build implementation prompt
        model_name = os.path.basename(report_path).replace(".md", "")
        prompt = f"""
根据以下论文分析结果，生成 Python 工程实现：

论文摘要:
{sections.get('abstract', '')[:1000]}

方法论:
{sections.get('methodology', '')[:1000]}

要求:
1. 生成 `{model_name}.py` — 核心算法模块（含类定义、方法、文档字符串）
2. 生成 `test_{model_name}.py` — 单元测试（覆盖主要功能）
3. 生成 `example_{model_name}.ipynb` — Jupyter 使用示例
4. 所有代码使用 NumPy，可选的 SciPy
5. 添加类型注解(type hints)
"""

        # Generate code skeleton
        code = f'''"""
{sections.get("abstract", "Model description")[:200]}
Generated by Hermes Research Hub | {datetime.now().isoformat()}
"""

import numpy as np
from dataclasses import dataclass, field
from typing import Optional, Callable


@dataclass
class ModelConfig:
    """Configuration parameters for the hysteresis model."""
    sampling_rate: float = 1000.0
    dt: float = field(init=False)

    def __post_init__(self):
        self.dt = 1.0 / self.sampling_rate


class HysteresisModel:
    """
    Base class for hysteresis models derived from IEEE paper analysis.

    Subclasses must implement:
        - simulate(input_signal: np.ndarray) -> np.ndarray
    """

    def __init__(self, config: Optional[ModelConfig] = None):
        self.config = config or ModelConfig()
        self.state = np.array([])
        self._validate_config()

    def _validate_config(self):
        """Validate model configuration."""
        if self.config.dt <= 0:
            raise ValueError("Sampling interval must be positive")

    def simulate(self, input_signal: np.ndarray) -> np.ndarray:
        """Run model simulation. Override in subclass."""
        raise NotImplementedError

    def __repr__(self):
        return f"<{self.__class__.__name__} | config: {self.config}>"
'''

        # write file
        module_path = os.path.join(target_dir, f"{model_name}.py")
        with open(module_path, "w") as f:
            f.write(code)

        logger.info(f"✅ Module generation: {module_path}")
        return module_path

    # ┌─────────────────── Batch assembly line ───────────────────────┐

    def run_full_pipeline(self, query_or_doi: str, is_doi: bool = False):
        """End-to-end pipeline: Search → Analysis → Code Generation"""
        if is_doi:
            report = self.analyze_paper(query_or_doi)
            if report:
                self.generate_code(report)
        else:
            papers = self.search_papers(query_or_doi, max_results=3)
            for p in papers:
                doi = p.get("externalIds", {}).get("DOI", "")
                if doi:
                    report = self.analyze_paper(doi)
                    if report:
                        self.generate_code(report)

        logger.info("🏁 The assembly line is completed!")

    # ──────── Status query ────────

    def status(self):
        """Show current warehouse status"""
        reports = []
        for f in os.listdir(RESEARCH_DIR):
            if f.endswith(".md"):
                reports.append(f)

        impls = []
        for root, dirs, files in os.walk(SCRIPT_DIR):
            if '.git' in root or 'agents' in root or 'research' in root or 'tests' in root:
                continue
            if 'src' in root:
                for f in files:
                    if f.endswith(".py"):
                        impls.append(os.path.relpath(os.path.join(root, f), SCRIPT_DIR))

        return {
            "reports": len(reports),
            "implementations": len(impls),
            "last_updated": datetime.now().isoformat()
        }


def cli():
    hub = ResearchHub()
    import argparse
    parser = argparse.ArgumentParser(description="Research-to-Code Pipeline")
    parser.add_argument("action", choices=["search", "analyze", "pipeline", "status"],
                       help="Operation type")
    parser.add_argument("--query", help="搜索关键词")
    parser.add_argument("--doi", help="论文 DOI")
    parser.add_argument("--max", type=int, default=5, help="最大搜索结果数")
    parser.add_argument("--report", help="分析报告路径（配合代码生成）")

    args = parser.parse_args()

    if args.action == "search":
        papers = hub.search_papers(args.query, args.max)
        for i, p in enumerate(papers[:args.max]):
            title = p.get("title", "N/A")
            doi = p.get("externalIds", {}).get("DOI", "")
            cites = p.get("citationCount", 0)
            print(f"\n  {i+1}. [{cites}c] {title[:65]}")
            if doi:
                print(f"     DOI: {doi}")

    elif args.action == "analyze":
        if not args.doi:
            print("❌ Requires --doi parameter")
            return
        hub.analyze_paper(args.doi)

    elif args.action == "pipeline":
        if args.doi:
            hub.run_full_pipeline(args.doi, is_doi=True)
        elif args.query:
            hub.run_full_pipeline(args.query)
        else:
            print("❌ Requires --doi or --query parameter")

    elif args.action == "status":
        s = hub.status()
        print(f"\n📊 Research hub status")
        print(f"📄 Analysis report: {s['reports']}")
        print(f"⚙️ Code implementation: {s['implementations']}")
        print(f"🕐 Last updated: {s['last_updated']}")


if __name__ == "__main__":
    cli()
