#!/usr/bin/env python3
"""
IEEE Control Algorithm Research Hub
Bridging academic research → engineering implementation

Research pipeline:
  [Paper Search] → [In-depth Analysis] → [Code Generation] → [CI/CD Verification]
     ieee_search.py  paper_analyzer.py   hub.py        pipeline.yml
"""

import os
import sys
import json
import logging
import subprocess
from datetime import datetime
from typing import Dict, Any, List

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S"
)
logger = logging.getLogger("IEEE-Hub")

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
HERMES_DIR = os.path.join(SCRIPT_DIR, "agents", "hermes")
RESEARCH_DIR = os.path.join(SCRIPT_DIR, "research", "reports")
IMPLEMENTATIONS_DIR = os.path.join(SCRIPT_DIR, "implementations")


class ResearchHub:
    """Central dispatch: paper analysis → code generation"""

    def __init__(self):
        os.makedirs(RESEARCH_DIR, exist_ok=True)
        os.makedirs(IMPLEMENTATIONS_DIR, exist_ok=True)

    # ───────── Research stage ─────────

    def search_papers(self, query: str, max_results: int = 5) -> List[Dict]:
        """Step 1: Search papers from multiple sources (Semantic Scholar + OpenAlex)"""
        sys.path.insert(0, HERMES_DIR)
        from ieee_search import search_papers as ss_search

        logger.info(f"🔍 Search papers: {query}")
        result = ss_search(query, max_results=max_results)
        papers = result.get("results", [])
        logger.info(f" → {len(papers)} papers found")
        return papers

    def analyze_paper(self, doi: str) -> str:
        """Step 2: In-depth analysis of the paper → Generate Markdown report"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_doi = doi.replace("/", "_").replace(".", "_")
        output = os.path.join(RESEARCH_DIR, f"analysis_{safe_doi}.md")

        logger.info(f"📖 analysis paper: {doi}")
        result = subprocess.run(
            [sys.executable, os.path.join(HERMES_DIR, "paper_analyzer.py"),
             "--doi", doi, "--lang", "zh", "--output", output],
            capture_output=True, text=True, timeout=60
        )

        if os.path.exists(output):
            logger.info(f" ✅ Report saving: {output}")
            return output
        else:
            logger.error(f" ❌ Analysis failed: {result.stderr[:200]}")
            return ""

    # ───────── Code generation phase ─────────

    def generate_code(self, report_path: str, category: str = "hysteresis") -> str:
        """Step 3: Extract the mathematical model from the analysis report to generate code"""
        target_dir = os.path.join(IMPLEMENTATIONS_DIR, category)
        os.makedirs(target_dir, exist_ok=True)

        logger.info(f"⚙️ Generated code: {os.path.basename(report_path)} → {category}/")

        # Read the report and extract the mathematical model description
        with open(report_path, encoding="utf-8") as f:
            report = f.read()

        # Extract abstract and methodology parts
        sections = {"abstract": "", "methodology": "", "innovation": ""}
        current = ""
        for line in report.split("\n"):
            if "## 📝 Original summary" in line:
                current = "abstract"
            elif "## 🔬 Methodological analysis" in line:
                current = "methodology"
            elif "### innovative point" in line or "## 🏷️" in line:
                current = "innovation"
            elif line.startswith("## ") and current:
                current = ""

            if current in sections:
                sections[current] += line + "\n"

        # Build implementation prompt
        model_name = os.path.basename(report_path).replace(".md", "")
        prompt = f"""
Based on the analysis results of the following papers, a Python project implementation is generated:

Paper abstract:
{sections.get('abstract', '')[:1000]}

Methodology:
{sections.get('methodology', '')[:1000]}

Require:
1. Generate `{model_name}.py` — core algorithm module (including class definition, method, documentation string)
2. Generate `test_{model_name}.py` — unit test (covers main functions)
3. Generate `example_{model_name}.ipynb` — Jupyter usage example
4. All code uses NumPy, optional SciPy
5. Add type annotations (type hints)
"""

        # Generate code skeleton
        code = f'''"""
{sections.get("abstract", "Model description")[:200]}
Generated by Hermes Research Hub | {datetime.now().isoformat()}
"""

import numpy as np
from dataclasses import dataclass, field
from typing import Optional, Callable


@dataclass
class ModelConfig:
    """Configuration parameters for the hysteresis model."""
    sampling_rate: float = 1000.0
    dt: float = field(init=False)

    def __post_init__(self):
        self.dt = 1.0 / self.sampling_rate


class HysteresisModel:
    """
    Base class for hysteresis models derived from IEEE paper analysis.

    Subclasses must implement:
        - simulate(input_signal: np.ndarray) -> np.ndarray
    """

    def __init__(self, config: Optional[ModelConfig] = None):
        self.config = config or ModelConfig()
        self.state = np.array([])
        self._validate_config()

    def _validate_config(self):
        """Validate model configuration."""
        if self.config.dt <= 0:
            raise ValueError("Sampling interval must be positive")

    def simulate(self, input_signal: np.ndarray) -> np.ndarray:
        """Run model simulation. Override in subclass."""
        raise NotImplementedError

    def __repr__(self):
        return f"<{self.__class__.__name__} | config: {self.config}>"
'''

        #Write file
        module_path = os.path.join(target_dir, f"{model_name}.py")
        with open(module_path, "w") as f:
            f.write(code)

        logger.info(f" ✅ Module generation: {module_path}")
        return module_path

    # ┌──────────────────── Batch assembly line ────────────────────────┐

    def run_full_pipeline(self, query_or_doi: str, is_doi: bool = False):
        """End-to-end pipeline: Search → Analysis → Code Generation"""
        if is_doi:
            report = self.analyze_paper(query_or_doi)
            if report:
                self.generate_code(report)
        else:
            papers = self.search_papers(query_or_doi, max_results=3)
            for p in papers:
                doi = p.get("externalIds", {}).get("DOI", "")
                if doi:
                    report = self.analyze_paper(doi)
                    if report:
                        self.generate_code(report)

        logger.info("🏁 Pipeline completed!")

    # ──────── Status query ────────

    def status(self):
        """Show current warehouse status"""
        reports = []
        for f in os.listdir(RESEARCH_DIR):
            if f.endswith(".md"):
                reports.append(f)

        impls = []
        for root, dirs, files in os.walk(IMPLEMENTATIONS_DIR):
            for f in files:
                if f.endswith(".py"):
                    impls.append(os.path.relpath(os.path.join(root, f), IMPLEMENTATIONS_DIR))

        return {
            "reports": len(reports),
            "implementations": len(impls),
            "last_updated": datetime.now().isoformat()
        }


def cli():
    hub = ResearchHub()
    import argparse
    parser = argparse.ArgumentParser(description="Research-to-Code Pipeline")
    parser.add_argument("action", choices=["search", "analyze", "pipeline", "status"],
                       help="operation type")
    parser.add_argument("--query", help="search keywords")
    parser.add_argument("--doi", help="Paper DOI")
    parser.add_argument("--max", type=int, default=5, help="Maximum number of search results")
    parser.add_argument("--report", help="Analysis report path (with code generation)")

    args = parser.parse_args()

    if args.action == "search":
        papers = hub.search_papers(args.query, args.max)
        for i, p in enumerate(papers[:args.max]):
            title = p.get("title", "N/A")
            doi = p.get("externalIds", {}).get("DOI", "")
            cites = p.get("citationCount", 0)
            print(f"\n  {i+1}. [{cites}c] {title[:65]}")
            if doi:
                print(f"     DOI: {doi}")

    elif args.action == "analyze":
        if not args.doi:
            print("❌ requires --doi parameter")
            return
        hub.analyze_paper(args.doi)

    elif args.action == "pipeline":
        if args.doi:
            hub.run_full_pipeline(args.doi, is_doi=True)
        elif args.query:
            hub.run_full_pipeline(args.query)
        else:
            print("❌ requires --doi or --query argument")

    elif args.action == "status":
        s = hub.status()
        print(f"\n📊 Research hub status")
        print(f" 📄 Analysis report: {s['reports']}")
        print(f" ⚙️ Code implementation: {s['implementations']}")
        print(f" 🕐 Last updated: {s['last_updated']}")


if __name__ == "__main__":
    cli()
