#!/usr/bin/env python3
"""Daily/Weekly Research Summary Generator
usage:
    python daily_digest.py --config templates/research_domains.yaml --mode daily
    python daily_digest.py --config templates/research_domains.yaml --mode weekly --export notion
"""

import sys, os, json, argparse, urllib.request, urllib.parse, time, yaml
from datetime import datetime


def load_config(path):
    with open(path, "r") as f:
        return yaml.safe_load(f)


def search_domain(name, cfg, max_results=5):
    keywords = cfg.get("keywords", [])
    year_start = cfg.get("year_start", 2020)
    min_cites = cfg.get("min_citations", 0)
    priority = cfg.get("priority", 5)

    all_papers = {}
    seen = set()

    for kw in keywords[:2]: # Only search the first 2 keywords to reduce the number of requests
        q = urllib.parse.quote(kw)
        url = f"https://api.semanticscholar.org/graph/v1/paper/search?query={q}&limit={max_results}&year={year_start}-&fields=title,authors,year,journal,externalIds,abstract,citationCount,url,venue,publicationDate,openAccessPdf"
        for attempt in range(3):
            try:
                req = urllib.request.Request(url, headers={"User-Agent": "HermesAgent/2.0"})
                with urllib.request.urlopen(req, timeout=12) as r:
                    data = json.loads(r.read())
                for p in data.get("data", []):
                    pid = p.get("paperId", "")
                    if pid and pid not in seen:
                        seen.add(pid)
                        p["_domain"] = name
                        p["_priority"] = priority
                        p["_min_cites"] = min_cites
                        all_papers[pid] = p
                break  # success, don't retry
            except urllib.error.HTTPError as e:
                if e.code == 429:
                    wait = (attempt + 1) * 3
                    time.sleep(wait)
                else:
                    break
            except Exception:
                break
        time.sleep(8) # Wait 8 seconds between each keyword to avoid 429

    papers = list(all_papers.values())
    papers = [p for p in papers if p.get("citationCount", 0) >= min_cites]
    papers.sort(key=lambda p: (-p.get("citationCount", 0), -p.get("year", 0)))
    return papers[:max_results]


def score_relevance(paper):
    """Overall Rating"""
    text = (paper.get("title", "") + " " + (paper.get("abstract") or "")).lower()
    terms = ["piezoelectric", "actuator", "hysteresis", "bouc-wen", "pmn",
             "control", "compensation", "inverse", "model", "positioning",
             "precision", "rate-dependent", "ferroelectric", "shear"]
    return sum(1 for t in terms if t in text)


def generate_report(all_results, mode="daily", config=None):
    """Generate summary report"""
    now = datetime.now()
    title = "Daily" if mode == "daily" else "Weekly"
    date_str = now.strftime("%Y-%m-%d")

    report = f"# 📊 Piezoelectric Control Research {title} — {date_str}\n\n"
    report += f"*Generated by Hermes Agent + ieee-search v2.0 | {now.strftime('%H:%M:%S')}*\n\n"
    report += "---\n\n"

    total_new = 0
    total_high = 0  # score >= 8

    for domain_name, papers in all_results.items():
        if not papers:
            continue
        domain_cfg = config.get("research_domains", {}).get(domain_name, {})
        priority = domain_cfg.get("priority", 5)
        desc = domain_cfg.get("description", "")

        report += f"## {domain_name}"
        report += f" ({len(papers)} papers)" if len(papers) else ""
        report += f" *Priority: {priority}/10*\n"
        if desc:
            report += f"> {desc}\n"
        report += "\n"

        for i, p in enumerate(papers, 1):
            score = score_relevance(p)
            if score >= 8:
                total_high += 1
            stars = "⭐" * min(5, score // 2) + "☆" * max(0, 5 - score // 2)
            title = p.get("title", "N/A")
            year = p.get("year", "?")
            cites = p.get("citationCount", 0)
            venue = p.get("journal", {}) or p.get("venue", {})
            venue_name = venue.get("name", "") if isinstance(venue, dict) else str(venue)
            doi = p.get("externalIds", {}).get("DOI", "")
            arxiv = p.get("externalIds", {}).get("ArXiv", "")

            is_high = " 🔥" if score >= 8 else ""
            is_ieee = " [IEEE]" if "IEEE" in str(venue) else ""

            report += f"### {i}. {title}{is_high}\n\n"
            report += f"| Properties | Content |\n|------|------|\n"
            report += f"| Journal | {venue_name}{is_ieee} |\n"
            report += f"| year | {year} |\n"
            report += f"| citations | {cites} |\n"
            if doi:
                report += f"| DOI | [{doi}](https://doi.org/{doi}) |\n"
            if arxiv:
                report += f"| arXiv | [{arxiv}](https://arxiv.org/abs/{arxiv}) |\n"
            report += f"| Relevance | {stars} ({score}/14) |\n"

            abstract = (p.get("abstract") or "")[:200]
            if abstract:
                report += f"\n> {abstract}...\n"

            report += "\n"

            total_new += 1

        report += "---\n\n"

    # Summary
    report += f"## 📈 Statistics\n\n"
    report += f"- Total number of papers: {total_new}\n"
    report += f"- High correlation (score ≥ 8): {total_high}\n"
    report += f"- Involved areas: {len([k for k,v in all_results.items() if v])}\n"
    report += "\n---\n"
    report += f"*Next update: {('tomorrow' if mode == 'daily' else 'next week')} | ieee-search v2.0*\n"

    return report


def main():
    parser = argparse.ArgumentParser(description="Research Summary Generator")
    parser.add_argument("--config", required=True, help="Research field configuration file")
    parser.add_argument("--mode", choices=["daily", "weekly"], default="daily")
    parser.add_argument("--max-per-domain", type=int, default=5)
    parser.add_argument("--output", help="output file")
    parser.add_argument("--export", choices=["file", "notion", "none"], default="file")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    config = load_config(args.config)
    domains = config.get("research_domains", {})
    output_cfg = config.get("output", {})

    max_per = args.max_per_domain or output_cfg.get("max_papers_per_domain", 5)
    lang = output_cfg.get("language", "zh")

    print(f"\n  {'='*55}")
    print(f"  ieee-search v2.0 — {'Daily' if args.mode == 'daily' else 'Weekly'} Research Digest")
    print(f"  {'='*55}")
    print(f"  Searching {len(domains)} research domains...")
    print(f"  Max {max_per} papers per domain\n")

    all_results = {}
    # Sort by priority
    sorted_domains = sorted(domains.items(), key=lambda x: -x[1].get("priority", 0))

    for domain_name, domain_cfg in sorted_domains:
        try:
            papers = search_domain(domain_name, domain_cfg, max_results=max_per)
            all_results[domain_name] = papers
            print(f"  {'[OK]':6} {domain_name}: {len(papers)} papers (priority {domain_cfg.get('priority','?')})")
        except Exception as e:
            print(f"  {'[ERR]':6} {domain_name}: {e}")
            all_results[domain_name] = []

    report = generate_report(all_results, args.mode, config)

    if args.dry_run:
        print(f"\n{report}")
        return

    # Save
    ts = datetime.now().strftime("%Y%m%d")
    out_dir = os.path.expanduser("~/.hermes/research_reports")
    os.makedirs(out_dir, exist_ok=True)
    out_file = args.output or os.path.join(out_dir, f"{args.mode}_digest_{ts}.md")

    with open(out_file, "w", encoding="utf-8") as f:
        f.write(report)

    print(f"\n  Report saved: {out_file}")
    print(f"  Total papers: {sum(len(v) for v in all_results.values())}")
    print(f"\n{report[:3000]}...")


if __name__ == "__main__":
    main()
